### ISSUE TITLE
vars.Fetch should take only var key to resolve value

### ISSUE THREAD

**Issue by Chaitanyabsprip** [rwxrob/bonzai#274]

**Comment by rwxrob** [comment]
I woke up with the idea of adding the vars.Driver to bonzai again and actually triggering persistence from Set and hinting at it with Var.Persist. Let me try that.

**Comment by rwxrob** [comment]
I am warming up to the idea of having both `bonzai.Persistence` and `Cmd.WithPersistence()` as well. I feel like if we do this right the only thing command developers would ever need would be `Cmd.Vars` and `Cmd.Set/Get`. All the other stuff is just external tools for dealing with specific `bonzai.Persister` implementations. In fact, I *really* want this because I can create a cloud-based persister for stuff I want to be able to use all over and leave the other stuff to localized things. Sounds like you like it as well. I'll go for it during my next mini-sprint (probably tonight).

**Comment by Chaitanyabsprip** [comment]
You're right, I like it as well, I just have a question about the scope of the Persister, see https://github.com/rwxrob/bonzai/issues/275#issuecomment-2492201368

**Comment by rwxrob** [comment]
Just merged a PR related to this, let's see if it works out
